### ISSUE TITLE
Bulk issue for tracking frontend development.

### ISSUE THREAD

**Issue by 3h5t4tvz8etx1op2** [deweb-project/deweb#1]
So basically we need a frontend, nothing special.

Frontend source code resides in `frontend/` directory, and is launching thru `gui/main.go`.

Frontend is able to talk with the backend directly, thanks to lorca, list of all available functions is available in `gui/main.go`, look for `ui.Bind` function calls. You are able to talk to the function as [in here](https://github.com/deweb-project/deweb/blob/97a32f59418051ef65b66bd19f0fda5653517360/frontend/index.html#L25)

```html
<p>Your ID: <code id="userid">Generating...</code></p>
<script>
  getSelfID().then((v) => {
    document.getElementById("userid").innerText = v.ID
  })
</script>
```

This is what abilities I would expect from a frontend:
 - [ ] Check self id `GetSelfID`
 - [ ] Conversations 
   - [ ] List all conversations `LoadConversationList`
   - [ ] Start new conversations `CreateConversation`
   - [ ] Add users to conversation `SendInvitation` and on the other side, `AcceptInvitation`
   - [ ] Ban user from conversation `BanUser`
   - [ ] Chat in conversation (text only, no images as for now) `SendMessage`
 - [ ] (optional) A debug screen which list all tasks currently in queue `Queue.Tasks`
